language: node_js
node_js:
- '8'
cache: yarn
sudo: required
addons:
  chrome: beta
  sauce_connect: true
notifications:
    email:
        recipients:
            - preview-alerts@box.com
jobs:
  include:
  - script: yarn run ci
  - if: type = cron
        before_script:
        - python -m SimpleHTTPServer &
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - sleep 5
        script: travis_retry yarn run functional-tests-ci
